# yaml-language-server: $schema=../../schema/local.json
binds:
- port: 3000
  listeners:
  - routes:
    - policies:
        cors:
          allowOrigins:
          - "*"
          allowHeaders:
          - "*"
      backends:
      - mcp:
          targets:
          - name: sse
            sse:
              host: mcp-everything
              port: 3001
              path: /sse