[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3

# Flake8 cannot be configured via pyproject.toml `flake8-pyproject`
[tool.flake8]
max-line-length = 88
extend-ignore = "E203"
exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
]

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[tool.ruff]
line-length = 88
target-version = "py310"
# E=pycodestyle errors, F=pyflakes, I=isort, B=flake8-bugbear, UP=pyupgrade
select = ["E", "F", "I", "B", "UP"]
ignore = ["E203"]
# Enable auto-fixing
fix = true
unsafe-fixes = true
# Sort imports
fix-only = true
